language: python

python: "3.6.4"

before_install:
  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./OZW_Log.txt
  
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all