homeassistant:
  customize_glob:
    binary_sensor.router_slaapkamer_router:
      friendly_name: "Slaapkamer Luuk - Zigbee2MQTT Router"
    sensor.router_slaapkamer_linkquality:
      friendly_name: "Slaapkamer Luuk - Zigbee2MQTT Router - Connection"
      unit_of_measurement: RSSI
    binary_sensor.router_woonkamer_router:
      friendly_name: "Woonkamer - Zigbee2MQTT Router"
    sensor.router_woonkamer_linkquality:
      friendly_name: "Woonkamer - Zigbee2MQTT Router - Connection"
      unit_of_measurement: RSSI
    binary_sensor.router_kantoor_router:
      friendly_name: "Kantoor - Zigbee2MQTT Router"
    sensor.router_kantoor_linkquality:
      friendly_name: "Kantoor - Zigbee2MQTT Router - Connection"
      unit_of_measurement: RSSI

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 300 # Update this to the number of seconds you wish

sensor:
  - platform: mqtt
    name: zigbee2mqtt hub
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless

group:
  zigbee2mqtt_controller:
    name: zigbee2mqtt
    entities:
      - input_boolean.zigbee_permit_join
      - timer.zigbee_permit_join
      - lock.zigbee2mqtt
      - sensor.zigbee2mqtt_hub
      - binary_sensor.router_slaapkamer_router
      - sensor.router_slaapkamer_linkquality
      - binary_sensor.router_woonkamer_router
      - sensor.router_woonkamer_linkquality
      - binary_sensor.router_kantoor_router
      - sensor.router_kantoor_linkquality

# Availability and lock status of ZigBee network
lock:
  - platform: mqtt
    name: Zigbee2mqtt
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_lock: "false"
    payload_unlock: "true"
    retain: true
    availability_topic: "zigbee2mqtt/bridge/state"

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
        to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'true'
    - service: timer.start
      data:
        entity_id: timer.zigbee_permit_join
  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
        to: 'off'
    action:
    - data:
        payload: 'false'
        topic: zigbee2mqtt/bridge/config/permit_join
      service: mqtt.publish
    - data:
        entity_id: timer.zigbee_permit_join
      service: timer.cancel
    hide_entity: true
  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    hide_entity: true
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'false'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee_permit_join