remote:
  - platform: harmony
    name: Woonkamer Harmony
    host: !secret HARMONY_HOST

group:
  harmony_woonkamer:
    name: Harmony - Woonkamer
    entities:
      - remote.woonkamer_harmony
      - sensor.harmony_woonkamer
      - input_select.harmony_woonkamer

sensor:
  - platform: template
    sensors:
      harmony_woonkamer:
        value_template: '{{ states.remote.woonkamer_harmony.attributes.current_activity }}'
        friendly_name: 'Woonkamer - Harmony - Activiteit'
        
input_select:
  harmony_woonkamer:
    name: Woonkamer - Harmony
    options:
     - Selecteer activiteit
     - Kodi Media Player
     - Apple TV kijken
     - Tv kijken
     - Luisteren naar Sonos
     - Joki en Jet
     - Uit
    initial: Selecteer activiteit

automation:
  - alias: 'TV Room Controls'
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.harmony_woonkamer
    action:
      - service: remote.turn_on
        data_template:  
          entity_id: remote.woonkamer_harmony
          activity: >-
            {% if is_state("input_select.harmony_woonkamer", "Uit") %}-1
            {% elif is_state("input_select.harmony_woonkamer", "Kodi Media Player") %}33803898
            {% elif is_state("input_select.harmony_woonkamer", "Apple TV kijken") %}21771737
            {% elif is_state("input_select.harmony_woonkamer", "Tv kijken") %}32097142
            {% elif is_state("input_select.harmony_woonkamer", "Luisteren naar Sonos") %}21771601
            {% elif is_state("input_select.harmony_woonkamer", "Joki en Jet") %}33803916
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony_woonkamer
        data_template:
          option: "Selecteer activiteit"
  - alias: 'Start Joki en Jet'
    initial_state: true
    hide_entity: true
    trigger:
      - entity_id: sensor.harmony_woonkamer
        platform: state
        to: Joki en Jet
    action:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kodi_media_player
          media_content_id: plugin://plugin.video.youtube/play/?playlist_id=PLOaricAENKs03OxaOVqhyebed_WQEwg6Z&play=1&order=shuffle
          media_content_type: video
      - service: light.turn_on
        data:
          entity_id: light.ambilight
          effect: "HDMI"
  - alias: 'Stop Joki en Jet'
    initial_state: true
    hide_entity: true
    trigger:
      - entity_id: sensor.harmony_woonkamer
        platform: state
        from: Joki en Jet
    action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi_media_player
    - service: light.turn_off
      data:
        entity_id: light.ambilight