group:
  wallpanel_kantoor:
    name: Wallpanel - Kantoor
    entities:
      - camera.wallpanel_kantoor_camera
      - sensor.wallpanel_kantoor_batterij
      - sensor.wallpanel_kantoor_temperatuur
      - sensor.wallpanel_kantoor_licht
      - sensor.wallpanel_kantoor_magnetisch_veld
      - sensor.wallpanel_kantoor_luchtdruk
      - sensor.wallpanel_kantoor_qr_code
      - binary_sensor.wallpanel_kantoor_beweging
      - binary_sensor.wallpanel_kantoor_gezicht

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.178.59:2971/camera/stream
    name: "WallPanel - Kantoor - Camera"

sensor:
  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/battery"
    name: "WallPanel - Kantoor - Batterij"
    unit_of_measurement: "%"
    value_template: ''

  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/temperature"
    name: "WallPanel - Kantoor - Temperatuur"
    unit_of_measurement: "°C"
    value_template: ''

  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/light"
    name: "WallPanel - Kantoor - Licht"
    unit_of_measurement: "lx"
    value_template: ''
    
  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/magneticField"
    name: "WallPanel - Kantoor - Magnetisch veld"
    unit_of_measurement: "uT"
    value_template: ''

  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/pressure"
    name: "WallPanel - Kantoor - Luchtdruk"
    unit_of_measurement: "hPa"
    value_template: ''
    
  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/qrcode"
    name: "WallPanel - Kantoor - QR Code"
    value_template: ''

binary_sensor:
  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/motion"
    name: "WallPanel - Kantoor - Beweging"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion 

  - platform: mqtt
    state_topic: "wallpanel/kantoor/sensor/face"
    name: "WallPanel - Kantoor - Gezicht"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion