group:
  wallpanel_woonkamer:
    name: Wallpanel - Woonkamer
    entities:
      - camera.wallpanel_woonkamer_camera
      - sensor.wallpanel_woonkamer_batterij
      - sensor.wallpanel_woonkamer_licht
      - sensor.wallpanel_woonkamer_qr_code
      - binary_sensor.wallpanel_woonkamer_beweging
      - binary_sensor.wallpanel_woonkamer_gezicht

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.178.54:2971/camera/stream
    name: "WallPanel - Woonkamer - Camera"

sensor:
  - platform: mqtt
    state_topic: "wallpanel/woonkamer/sensor/battery"
    name: "WallPanel - Woonkamer - Batterij"
    unit_of_measurement: "%"
    value_template: "{{ value_json.value }}"

  - platform: mqtt
    state_topic: "wallpanel/woonkamer/sensor/light"
    name: "WallPanel - Woonkamer - Licht"
    unit_of_measurement: "lx"
    value_template: "{{ value_json.value }}"
    
  - platform: mqtt
    state_topic: "wallpanel/woonkamer/sensor/qrcode"
    name: "WallPanel - Woonkamer - QR Code"
    value_template: "{{ value_json.value }}"

binary_sensor:
  - platform: mqtt
    state_topic: "wallpanel/woonkamer/sensor/motion"
    name: "WallPanel - Woonkamer - Beweging"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion 

  - platform: mqtt
    state_topic: "wallpanel/woonkamer/sensor/face"
    name: "WallPanel - Woonkamer - Gezicht"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion