homeassistant:
  customize_glob:
    light.berging:
      friendly_name: "Berging - Verlichting"
    light.berging_1:
      friendly_name: "Berging - Lamp #1"
    light.berging_2:
      friendly_name: "Berging - Lamp #2"
    light.berging_3:
      friendly_name: "Berging - Lamp #3"
    light.garderobe:
      friendly_name: "Garderobe - Verlichting"
    light.garderobe_1:
      friendly_name: "Garderobe - Lamp #1"
    light.garderobe_2:
      friendly_name: "Garderobe - Lamp #2"
    light.garderobe_3:
      friendly_name: "Garderobe - Lamp #3"
    light.kantoor:
      friendly_name: "Kantoor - Verlichting"
    light.kantoor_1:
      friendly_name: "Kantoor - Lamp #1"
    light.kantoor_2:
      friendly_name: "Kantoor - Lamp #2"
    light.kantoor_3:
      friendly_name: "Kantoor - Lamp #3"
    light.wc_beneden:
      friendly_name: "WC Beneden - Verlichting"
    light.wc_beneden_1:
      friendly_name: "WC Beneden - Lamp #1"

group:
  tradfri_berging:
    name: Tr책dfri Devices - Berging
    entities:
      - light.berging
      - light.berging_1
      - light.berging_2
      - light.berging_3
  tradfri_garderobe:
    name: Tr책dfri Devices - Garderobe
    entities:
      - light.garderobe
      - light.garderobe_1
      - light.garderobe_2
      - light.garderobe_3
  tradfri_kantoor:
    name: Tr책dfri Devices - Kantoor
    entities:
      - light.kantoor
      - light.kantoor_1
      - light.kantoor_2
      - light.kantoor_3
  tradfri_wc_beneden:
    name: Tr책dfri Devices - Wc beneden
    entities:
      - light.wc_beneden
      - light.wc_beneden_1